const LANGUAGE_STORAGE_KEY = "burger-dungeon-language";
const DEFAULT_LANGUAGE = "en";

const TRANSLATIONS = {
  en: {
    game_title_line_1: "BURGER",
    game_title_line_2: "DUNGEON",
    menu_start_run: "Start Run",
    menu_join_run: "Join Run",
    menu_settings: "Settings",
    menu_ascend: "Descend",
    menu_host_run: "Host",
    menu_hosted_run: "Hosted Run",
    menu_resolve_party: "Resolve Party",
    menu_room_code: "Room Code",
    menu_players: "Players",
    menu_character_turn: "Character Turn",
    menu_find: "Find",
    menu_join: "Join",
    menu_waiting: "Waiting",
    menu_run_setup: "Run Setup",
    menu_difficulty: "Difficulty",
    menu_character: "Character",
    menu_party_size: "Party Size",
    menu_difficulty_casual: "Casual",
    menu_difficulty_hardmode: "Hardmode",
    menu_character_kostya: "Kostya",
    menu_character_patrick: "Patrick",
    menu_character_jacob: "Jacob",
    menu_class_assassin: "Assassin",
    menu_class_gambler: "Gambler",
    menu_class_goalkeeper: "Wingman",
    menu_party_solo: "Solo",
    menu_party_duo: "Duo",
    menu_party_trio: "Trio",
    menu_join_hint: "Enter a 6 digit room code.",
    menu_join_invalid_code: "Room code must be exactly 6 digits.",
    menu_join_found: "Lobby found: {count}/{max} players.",
    menu_join_not_found: "No hosted run was found with that code.",
    menu_join_success: "Joined the lobby.",
    menu_lobby_full: "That lobby is already full.",
    menu_lobby_already_started: "That run has already started.",
    menu_lobby_started: "Run started. Launching game...",
    menu_multiplayer_backend_missing: "Online multiplayer UI is ready, but GitHub Pages still needs a real backend service for live rooms.",
    menu_multiplayer_unavailable: "Multiplayer is unavailable right now.",
    menu_local_multiplayer_hint: "Local multiplayer test mode is active. Open this same Live Server URL in more tabs to join.",
    menu_local_player_name: "Player {number}",
    menu_host_created: "Lobby created. Share code {code}.",
    menu_host_waiting_players: "Waiting for the rest of the party to join before Descend unlocks.",
    menu_host_waiting_picks: "Lobby is full. Players now take turns locking unique characters.",
    menu_host_ready_to_ascend: "Lobby is full and all characters are locked. Descend is ready.",
    menu_host_turn_waiting: "No hosted run yet.",
    menu_host_turn_fill_lobby: "Waiting for the lobby to fill.",
    menu_host_turn_ready: "All picks are locked in.",
    menu_host_turn_started: "The run has started.",
    menu_host_turn_pick: "{player} chooses now.",
    menu_host_player_name: "Player 1 (Host)",
    menu_open_slot: "Open Slot {slot}",
    menu_waiting_for_player: "Waiting for player...",
    menu_waiting_for_host_start: "Waiting for the host to start the run.",
    menu_pick_turn_now: "It is your turn to lock a character.",
    menu_pick_turn_wait: "Wait for your turn to lock a character.",
    menu_character_taken: "That character is already taken.",
    menu_character_taken_badge: "Taken",
    menu_only_host_start: "Only the host can start the run.",
    menu_role_host: "Host",
    menu_role_player: "Player {number}",
    menu_character_unselected: "Character pending",
    info_hp_sp: "{hp} HP / {sp} SP",
    info_kostya_playstyle: "Katana fighter that can counter attacks and summon dark forces to help him in battle.",
    info_patrick_playstyle: "Revolverist with high damage output, moderate self and team sustain utilities.",
    info_jacob_playstyle: "Defensive tank with a high skill ceiling that relies heavily on team support.",
    settings_title: "Settings",
    settings_music_volume: "Music Volume",
    settings_sfx_volume: "SFX Volume",
    settings_language: "Language",
    settings_hp_saturation: "Screen Desaturation",
    settings_dev_mode: "Developer Mode",
    settings_on: "On",
    settings_off: "Off",
    language_en: "English",
    language_pl: "Polish",
    loading_descending: "Descending",
    ui_level_short: "LVL",
    ui_hp_short: "HP",
    ui_sp_short: "SP",
    ui_lc_short: "LC",
    ui_sh_short: "SH",
    ui_defense_short: "DEFENSE",
    ui_mobile_short: "MOBILE",
    ui_mode_play: "Play",
    ui_mode_inspect: "Inspect",
    action_katana: "Katana",
    action_casts: "Casts",
    action_slash: "Slash",
    action_dash: "Dash",
    action_lunge: "Lunge",
    action_decay_curse: "Decay Curse",
    action_crippling_stab: "Crippling\nStab",
    action_action_recall: "Action\nRecall",
    action_mass_infection: "Mass\nInfection",
    action_ghost: "Ghost",
    action_wraith: "Wraith",
    action_deep_focus: "Deep Focus",
    action_dark_plating: "Dark\nPlating",
    action_field_promotion: "Field\nPromotion",
    action_shadow: "Shadow",
    action_kick: "Kick",
    action_defend: "Defend",
    action_ball_menu: "Ball",
    action_support_menu: "Support",
    action_group_buff: "Group Buff",
    action_good_vibes: "Good Vibes",
    action_fireball: "Fireball",
    action_slowball: "Slowball",
    action_block: "Defend+",
    action_corner_shot: "Corner Shot",
    action_goal: "Goal",
    action_friendly_chatter: "Friendly\nChatter",
    action_guard: "Guard",
    action_group_buff_plus: "Group Buff+",
    action_volley: "Volley",
    action_back: "X",
    action_coin_flip: "Coin Flip",
    action_revolver: "Revolver",
    action_aces: "Aces",
    action_inventory: "Inventory",
    action_piercing_shot: "Piercing\nShot",
    action_hollow_shot: "Hollow Shot",
    action_magnum_shot: "Magnum Shot",
    action_bullet_storm: "Bullet Storm",
    action_quickdrawer: "Quickdrawer",
    action_coin_toss: "Coin Toss",
    action_feelin_fine: "Feelin' Fine",
    action_ace_of_hearts: "Ace\nof Hearts",
    action_ace_of_spades: "Ace\nof Spades",
    action_ace_of_diamonds: "Ace\nof Diamonds",
    action_ace_of_clubs: "Ace\nof Clubs",
    action_burger_item: "Burger",
    action_bomb_item: "Bomb",
    action_cherry_item: "Cherry",
    action_salad_item: "Salad",
    action_fires_item: "Fires",
    action_ketchup_item: "Ketchup",
    battle_choose_target_prompt: "Choose your target\nPress Shift to cancel",
    battle_locked_target_prompt: "Front target locked\nPress Shift to cancel",
    battle_player_no_legal_move: "No legal moves left\nGain {sp} SP and skip the turn",
    debug_kill_all: "Kill All",
    debug_teleport: "Teleport",
    debug_refill_all: "Refill All",
    debug_slow_mo: "Slow Mo",
    debug_skip_turn: "Skip Turn",
    debug_counter_feedback: "COUNTER FX",
    debug_kostya_counter_egg: "1 HP Counter",
    word_action_singular: "action",
    word_action_plural: "actions",
    upgrade_title: "Upgrade Pick",
    upgrade_pick_hint: "Choose 1 permanent boost",
    ability_title: "Ability Pick",
    ability_pick_hint: "Choose 1 new skill",
    ability_confirm_prompt: "Are you sure?",
    ability_confirm_guard_solo_prompt: "Are you sure? This ability is useless in solo mode",
    ability_confirm_button: "Confirm",
    upgrade_locked: "MAXXED",
    upgrade_luck_expertise_name: "Luck Expertise",
    upgrade_luck_expertise_description: "+1% Heads\n+0.05 Lucky Charge gain",
    upgrade_slot_machine_name: "Slot Machine",
    upgrade_slot_machine_description: "+7 Max HP\n+0.5 Weakness Tolerance",
    upgrade_bullet_enhancement_name: "Bullet Enhancement",
    upgrade_bullet_enhancement_description: "+2 Revolver Damage",
    upgrade_sharper_blade_name: "Sharper Blade",
    upgrade_sharper_blade_description: "+1 Katana Damage\n+0.15 Counter Window",
    upgrade_corrupted_heart_name: "Corrupted Heart",
    upgrade_corrupted_heart_description: "+5 Max HP\n+4% SHP for Shadow",
    upgrade_darkness_pull_name: "Darkness Pull",
    upgrade_darkness_pull_description: "+10% Shadow gain",
    upgrade_applied_force_name: "Applied Force",
    upgrade_applied_force_description: "+1 Ball Damage\n+1% per Green hit",
    upgrade_endurance_training_name: "Endurance Training",
    upgrade_endurance_training_description: "+10 Max HP\n+1 Defense",
    upgrade_dribbling_mastery_name: "Dribbling Mastery",
    upgrade_dribbling_mastery_description: "+0.1 Melee Dodge\n+0.1 Ranged Dodge",
    reward_fireball_description: "Ball attack that ramps Fire power",
    reward_slowball_description: "Ball attack that ramps Slowness power",
    reward_block_description: "Upgrades Defend into a parry stance",
    reward_corner_shot_description: "Double damage ball and Weakness VI",
    reward_goal_description: "Summon a goal that protects the team when broken",
    reward_friendly_chatter_description: "Team sustain with Regen and Absorption",
    reward_guard_description: "Teammate-required guard stance with SP Regen",
    reward_group_buff_plus_description: "Stronger Group Buff with added Speed",
    reward_volley_description: "High-risk burst volley with stun payoff",
    reward_piercing_shot_description: "Pierce through enemies",
    reward_hollow_shot_description: "Deal more damage",
    reward_magnum_shot_description: "Stun enemies",
    reward_ace_of_spades_description: "Quickly regain SP",
    reward_ace_of_diamonds_description: "Buff your team",
    reward_ace_of_clubs_description: "Debuff enemy team",
    reward_bullet_storm_description: "Thats a lot of bullets",
    reward_quickdrawer_description: "Hit and slow down two enemies",
    reward_coin_toss_description: "Deal massive damage or nothing",
    reward_lunge_description: "Hit both enemies in line and stun the one behind",
    reward_decay_curse_description: "Curse enemies with Decay",
    reward_action_recall_description: "Shadow repeats next katana action",
    reward_mass_infection_description: "Hit and curse enemy team",
    reward_ghost_description: "Double health with half the damage",
    reward_wraith_description: "Double damage with half the health",
    reward_deep_focus_description: "Prepare your deadly Counter",
    reward_crippling_stab_description: "Cripple and steal HP from enemy",
    reward_dark_plating_description: "Refill SHP and buff Shadow",
    inspect_katana_description: "Targets the front enemy\nDeals [damage]{damage} damage[/damage]\n[good]Green window:[/good] [good]+50%[/good] damage",
    inspect_slash_description: "Costs [resource]8 SP[/resource]\nAllows to pick the target\nDeals [damage]{damage} damage[/damage]\n[good]Green window:[/good] [good]+50%[/good] damage",
    inspect_lunge_description: "Costs [resource]16 SP[/resource]\nTargets [yellow]2[/yellow] enemies in line\nDeals [damage]{damage} damage[/damage] and [damage]{splashDamage} damage[/damage] to the target behind applying [bad]Stunned V[/bad] for 2 turns to the target behind\n[good]Green window:[/good] [good]+50%[/good] damage",
    inspect_decay_curse_description: "Costs [resource]16 SP[/resource] & [charge]20% Shadow[/charge]\nTargets the front enemy\nDeals [damage]{damage} damage[/damage] and applies [bad]Decaying III[/bad] for 4 turns\n[good]Green window:[/good] [good]+50%[/good] damage",
    inspect_crippling_stab_description: "Costs [resource]32 SP[/resource] & [charge]50% Shadow[/charge]\nTargets the front enemy\nDeals [damage]{damage} damage[/damage], steals [good]{heal} HP[/good], and applies [bad]Slowness I[/bad] for 2 turns\n[good]Green window:[/good] [good]+50%[/good] health steal",
    inspect_action_recall_description: "Costs [resource]24 SP[/resource] & [charge]40% Shadow[/charge]\nRequires Shadow in battle\nNext Katana move gets repeated by the Shadow dealing [damage]+100%[/damage] damage",
    inspect_mass_infection_description: "Costs [resource]24 SP[/resource] & [charge]40% Shadow[/charge]\nTargets the enemy team\nDeals [damage]{damage} damage[/damage] and applies [bad]Decaying II[/bad] for 3 turns to the enemy team\n[good]Green window:[/good] [good]+25%[/good] damage",
    inspect_ghost_description: "Costs [resource]56 SP[/resource] & [charge]100% Shadow[/charge]\nSummons a Ghost with [good]{hp} HP[/good] and [charge]{shp} SHP[/charge] to fight in battle\nGhost targets the front enemy, deals [damage]{damage} damage[/damage] per action and is likley target for enemies",
    inspect_wraith_description: "Costs [resource]56 SP[/resource] & [charge]100% Shadow[/charge]\nSummons a Wraith with [good]{hp} HP[/good] and [charge]{shp} SHP[/charge] to fight in battle\nWraith targets the front enemy, deals [damage]{damage} damage[/damage] per action and is mobile",
    inspect_deep_focus_description: "Costs [resource]56 SP[/resource]\nLose [yellow]Yellow[/yellow] and [good]Green[/good] dodge windows but increase [damage]Counter window[/damage] by [damage]2[/damage] and being able to Counter projectiles\n[damage]Counter window: +400%[/damage] damage\n[damage]Skips a turn[/damage]",
    inspect_dark_plating_description: "Costs [resource]32 SP[/resource] & [charge]50% Shadow[/charge]\nRequires Shadow in battle\nRefills Shadow to [charge]{shp} SHP[/charge] and applies [good]Speed II[/good] for 1 turn",
    inspect_casts_menu_description: "Opens Casts Action Menu\nContains: {contains}",
    inspect_field_promotion_description: "Costs [resource]48 SP[/resource] & [charge]80% Shadow[/charge]\nRequires Shadow in battle\nReplenishes [good]15% HP[/good] and [good]10% SHP[/good] missing for Shadow\nApplies [strength]Strength I[/strength] to Shadow for the level\n[strength]Strength power[/strength] stacks and wears down by 1 power for each level progressed",
    inspect_shadow_description: "Costs [resource]56 SP[/resource] & [charge]100% Shadow[/charge]\nSummons a Shadow with [good]{hp} HP[/good] and [charge]{shp} SHP[/charge] to fight in battle\nShadow targets the front enemy and deals [damage]{damage} damage[/damage] per action",
    inspect_kick_description: "Allows to pick the target\nDeals [damage]{damage} damage[/damage]\nHit up to [good]3[/good] green windows for stacking bonus damage",
    inspect_defend_description: "Must be your first action\nGain [resource]4 SP[/resource], [good]+1 Defense[/good], and [good]Resistance V[/good]\n[damage]Skips a turn[/damage]",
    inspect_block_description: "Must be your first action\nGain [resource]6 SP[/resource], [good]+1 Defense[/good], and [good]Resistance V[/good]\nPerfect melee dodges PARRY, stun, and grant [good]Speed I[/good] to Jacob's team for 2 turns\n[damage]Skips a turn[/damage]",
    inspect_group_buff_description: "Costs [resource]16 SP[/resource]\nApplies [strength]Strength IV[/strength] for 4 turns",
    inspect_group_buff_upgrade_description: "Costs [resource]16 SP[/resource]\nApplies [strength]Strength VI[/strength] for 4 turns and [good]Speed II[/good] for 2 turns",
    inspect_good_vibes_description: "Costs [resource]24 SP[/resource]\nHeals [good]{heal} HP[/good], applies [good]HP Regen II[/good], [resource]SP Regen II[/resource], and [cleansed]Cleansed V[/cleansed] for 2 turns\nApplies [bad]Slowness II[/bad] to Jacob for 1 turn",
    inspect_fireball_description: "Costs [resource]8 SP[/resource]\nBall attack dealing [damage]{damage} damage[/damage]\nApplies [bad]Fire IV[/bad] for 4 turns and each green hit adds +1 power",
    inspect_slowball_description: "Costs [resource]8 SP[/resource]\nBall attack dealing [damage]{damage} damage[/damage]\nApplies [bad]Slowness I[/bad] for 4 turns and each green hit adds +1 power",
    inspect_corner_shot_description: "Costs [resource]16 SP[/resource]\nBall attack dealing [damage]{damage} damage[/damage]\nApplies [bad]Weakness VI[/bad] for 2 turns",
    inspect_goal_description: "Costs [resource]28 SP[/resource]\nSummons a Goal with [good]{hp} HP[/good]\nWhen the Goal breaks, Jacob gains [good]Resistance IV[/good] and [absorption]Absorption II[/absorption] for 4 turns",
    inspect_friendly_chatter_description: "Costs [resource]28 SP[/resource]\nApplies [good]HP Regen IV[/good] and [absorption]Absorption II[/absorption] for 3 turns",
    inspect_guard_description: "Costs [resource]32 SP[/resource]\nRequires a living teammate\nGain [good]+1 Defense[/good] for 3 turns and [resource]SP Regen I[/resource] for 3 turns",
    inspect_volley_description: "Costs [resource]36 SP[/resource]\nBall attack dealing [damage]{damage} damage[/damage]\nEach green hit grants [damage]+100%[/damage] damage and failed windows deal [damage]-4[/damage]\nApplies [bad]Stunned IV[/bad] for up to 3 turns",
    inspect_ball_menu_description: "Opens Ball Action Menu\nContains: [damage]{contains}[/damage]",
    inspect_support_menu_description: "Opens Support Action Menu\nContains: {contains}",
    inspect_coin_flip_description: "Gain [charge]{luckyChargeGain} {luckyChargeWord}[/charge]\n[good]Heads land {chance}% of the time[/good] and grant [resource]{headsSp} SP[/resource]\nTails grant [resource]{tailsSp} SP[/resource] and apply [bad]Weakness I[/bad] for 2 turns\n[bad]Weakness Power[/bad] stacks and stores itself",
    inspect_lucky_charge_word_singular: "Lucky Charge",
    inspect_lucky_charge_word_plural: "Lucky Charges",
    inspect_revolver_menu_description: "Opens Revolver Action Menu\nContains: {contains}",
    inspect_katana_menu_description: "Opens Katana Action Menu\nContains: {contains}",
    inspect_aces_menu_description: "Opens Aces action menu\nContains: {contains}",
    inspect_inventory_menu_description: "Opens Inventory Menu\nContains: {contains}",
    inspect_inventory_empty: "[bad]Empty[/bad]",
    battle_jacob_guard_solo_warning: "GUARD needs a teammate and does nothing right now",
    inspect_revolver_shot_description: "Costs [charge]1 Lucky Charge[/charge]\nAllows to pick the target\nDeals [damage]{damage} damage[/damage]\n[yellow]Yellow window:[/yellow] [yellow]+25%[/yellow] damage\n[good]Green window:[/good] [good]+50%[/good] damage",
    inspect_piercing_shot_description: "Costs [resource]8 SP[/resource] & [charge]2 Lucky Charges[/charge]\nTargets [yellow]2[/yellow] front enemies\nDeals [damage]{damage} damage[/damage]\n[yellow]Yellow window:[/yellow] [yellow]+1[/yellow] target\n[good]Green window:[/good] [good]+2[/good] targets",
    inspect_hollow_shot_description: "Costs [resource]8 SP[/resource] & [charge]2 Lucky Charges[/charge]\nAllows to pick the target\nDeals [damage]{damage} damage[/damage] and applies [marked]Marked III[/marked] for 2 turns\n[yellow]Yellow window:[/yellow] [yellow]+25%[/yellow] damage\n[good]Green window:[/good] [good]+50%[/good] damage",
    inspect_magnum_shot_description: "Costs [resource]16 SP[/resource] & [charge]3 Lucky Charges[/charge]\nAllows to pick the target\nDeals [damage]{damage} damage[/damage] and applies [bad]Stunned X[/bad] for 1 turn\n[yellow]Yellow window:[/yellow] [yellow]+1[/yellow] turn\n[good]Green window:[/good] [good]+2[/good] turns",
    inspect_bullet_storm_description: "Costs [resource]24 SP[/resource] & [charge]4 Lucky Charges[/charge]\nAllows to pick the target\nReleases [yellow]3[/yellow] bullets towards the target, each dealing [damage]{damage} damage[/damage]\n[yellow]Yellow window:[/yellow] [yellow]+1[/yellow] bullet\n[good]Green window:[/good] [good]+3[/good] bullets",
    inspect_quickdrawer_description: "Costs [resource]24 SP[/resource] & [charge]3 Lucky Charges[/charge]\nAllows to pick the target\nDeals [damage]{damage} damage[/damage] to the target and the enemy behind it, applying [bad]Slowness II[/bad] for 1 turn to both\n[yellow]Yellow window:[/yellow] [yellow]+25%[/yellow] damage\n[good]Green window:[/good] [good]+50%[/good] damage",
    inspect_coin_toss_description: "Costs [resource]32 SP[/resource] & [charge]5 Lucky Charges[/charge]\nConsumes [charge]1 Lucky Charge[/charge]\nAllows to pick the target\nDeals [damage]{damage} damage[/damage]\n[info]No window:[/info] [damage]-100%[/damage] damage\n[yellow]Yellow window:[/yellow] [yellow]+600%[/yellow] damage\n[good]Green window:[/good] [good]+900%[/good] damage",
    inspect_feelin_fine_description: "Costs [resource]8 SP[/resource] & [charge]2 Lucky Charges[/charge]\nClears all bad status ailments and applies [cleansed]Cleansed {cleansedPower}[/cleansed] for 3 turns\nResets [bad]Stored Weakness[/bad]",
    inspect_ace_of_hearts_description: "Costs [resource]24 SP[/resource] & [charge]4 Lucky Charges[/charge]\nReplenishes [good]7 HP[/good] and applies [good]HP Regen III[/good] for 5 turns\n[damage]Skips a turn[/damage]",
    inspect_ace_of_spades_description: "Costs [charge]3 Lucky Charges[/charge]\nReplenishes [resource]7 SP[/resource] and applies [resource]SP Regen IV[/resource] for 3 turns",
    inspect_ace_of_diamonds_description: "Costs [resource]16 SP[/resource] & [charge]3 Lucky Charges[/charge]\nApplies [absorption]Absorption III[/absorption] and [strength]Strength III[/strength] for 4 turns to the ally team",
    inspect_ace_of_clubs_description: "Costs [resource]16 SP[/resource] & [charge]3 Lucky Charges[/charge]\nApplies [bad]Slowness I[/bad] and [marked]Marked III[/marked] for 4 turns to the enemy team",
    inspect_burger_item_description: "Replenishes [good]10 HP[/good] and applies [good]HP Regen I[/good] for 2 turns",
    inspect_bomb_item_description: "Deals [damage]25 damage[/damage] to all enemies and applies [bad]Stunned X[/bad] for 2 turns\nApplies [bad]Slowness II[/bad] for 1 turn to the user",
    inspect_cherry_item_description: "Applies [bad]Fire V[/bad] for 2 turns to all enemies\nApplies [strength]Strength X[/strength] for 2 turns to the user",
    inspect_salad_item_description: "Clears all bad status ailments and applies [cleansed]Cleansed X[/cleansed] for 3 turns",
    inspect_fires_item_description: "Replenishes [resource]10 SP[/resource] and applies [resource]SP Regen I[/resource] for 2 turns",
    inspect_ketchup_item_description: "Replenishes [good]15 HP[/good]\nApplies [strength]Strength IV[/strength] for 3 turns to all allies, including summons",
    battle_burger_item: "Burger replenished 10 HP and applied HP Regen I for 2 turns",
    battle_salad_item: "Salad cleared bad ailments and applied Cleansed {power} for {turns} turns",
    battle_cherry_item: "Cherry applied Fire {firePower} for {fireTurns} turns and Strength {strengthPower} for {strengthTurns} turns",
    battle_bomb_item: "Bomb dealt {damage} damage, stunned enemies with Stunned {stunPower} for {stunTurns} turns, and applied Slowness {slowPower} for {slowTurns} turn",
    battle_fires_item: "Fires replenished {sp} SP and applied SP Regen {power} for {turns} turns",
    battle_ketchup_item: "Ketchup replenished {heal} HP and applied Strength {power} for {turns} turns to all allies",
    jacob_defend: "Jacob braces for impact, gains {sp} SP, and fortifies his defense",
    jacob_group_buff: "Jacob rallied the team with Strength IV",
    jacob_group_buff_plus: "Jacob rallied the team with Strength VI and Speed II",
    jacob_good_vibes: "Good Vibes healed {heal} HP and refreshed the team",
    jacob_goal: "Jacob placed a Goal on the field",
    jacob_goal_break: "The Goal shattered and empowered Jacob with Resistance IV and Absorption II",
    jacob_friendly_chatter: "Friendly Chatter granted HP Regen IV and Absorption II",
    jacob_guard: "Jacob tightened his guard and started regenerating SP",
    jacob_kick: "Jacob kicked the ball for {damage} damage after {hits} clean hits",
    jacob_fireball: "Jacob launched a Fireball for {damage} damage after {hits} clean hits",
    jacob_slowball: "Jacob launched a Slowball for {damage} damage after {hits} clean hits",
    jacob_corner_shot: "Jacob fired a Corner Shot for {damage} damage after {hits} clean hits",
    jacob_volley: "Jacob unleashed a Volley for {damage} damage after {hits} clean hits"
  },
  pl: {
    game_title_line_1: "BURGER",
    game_title_line_2: "DUNGEON",
    menu_start_run: "Nowa gra",
    menu_join_run: "Dolacz",
    menu_settings: "Ustawienia",
    menu_ascend: "Zstap",
    menu_host_run: "Host",
    menu_hosted_run: "Hosted Run",
    menu_resolve_party: "Resolve Party",
    menu_room_code: "Kod pokoju",
    menu_players: "Gracze",
    menu_character_turn: "Tura postaci",
    menu_find: "Znajdz",
    menu_join: "Dolacz",
    menu_waiting: "Czekaj",
    menu_run_setup: "Ustawienia wyprawy",
    menu_difficulty: "Poziom trudnosci",
    menu_character: "Postac",
    menu_party_size: "Rozmiar druzyny",
    menu_difficulty_casual: "Normalny",
    menu_difficulty_hardmode: "Trudny",
    menu_character_kostya: "Kostek",
    menu_character_patrick: "Patryk",
    menu_character_jacob: "Jacob",
    menu_class_assassin: "Zabojca",
    menu_class_gambler: "Hazardzista",
    menu_class_goalkeeper: "Skrzydlowy",
    menu_party_solo: "Solo",
    menu_party_duo: "Duo",
    menu_party_trio: "Trio",
    menu_join_hint: "Wpisz 6 cyfrowy kod pokoju.",
    menu_join_invalid_code: "Kod pokoju musi miec dokladnie 6 cyfr.",
    menu_join_found: "Lobby znalezione: {count}/{max} graczy.",
    menu_join_not_found: "Nie znaleziono wyprawy z tym kodem.",
    menu_join_success: "Dolaczono do lobby.",
    menu_lobby_full: "To lobby jest juz pelne.",
    menu_lobby_already_started: "Ta wyprawa juz wystartowala.",
    menu_lobby_started: "Wyprawa wystartowala. Uruchamianie gry...",
    menu_multiplayer_backend_missing: "UI multiplayera jest gotowe, ale GitHub Pages nadal potrzebuje prawdziwego backendu do zywych lobby.",
    menu_multiplayer_unavailable: "Multiplayer jest teraz niedostepny.",
    menu_local_multiplayer_hint: "Aktywny jest lokalny tryb testowy multiplayera. Otworz ten sam adres Live Server w kolejnych kartach, aby dolaczac.",
    menu_local_player_name: "Gracz {number}",
    menu_host_created: "Lobby utworzone. Udostepnij kod {code}.",
    menu_host_waiting_players: "Czekamy na reszte druzyny, zanim przycisk Zstap sie odblokuje.",
    menu_host_waiting_picks: "Lobby jest pelne. Gracze wybieraja teraz unikalne postacie po kolei.",
    menu_host_ready_to_ascend: "Lobby jest pelne i wszystkie postacie sa zablokowane. Przycisk Zstap jest gotowy.",
    menu_host_turn_waiting: "Brak hostowanej wyprawy.",
    menu_host_turn_fill_lobby: "Czekanie na zapelnienie lobby.",
    menu_host_turn_ready: "Wszystkie wybory sa zatwierdzone.",
    menu_host_turn_started: "Wyprawa juz wystartowala.",
    menu_host_turn_pick: "Teraz wybiera: {player}.",
    menu_host_player_name: "Gracz 1 (Host)",
    menu_open_slot: "Wolny slot {slot}",
    menu_waiting_for_player: "Oczekiwanie na gracza...",
    menu_waiting_for_host_start: "Czekanie, az host uruchomi wyprawe.",
    menu_pick_turn_now: "To twoja tura na zablokowanie postaci.",
    menu_pick_turn_wait: "Poczekaj na swoja ture wyboru postaci.",
    menu_character_taken: "Ta postac jest juz zajeta.",
    menu_character_taken_badge: "Zajeta",
    menu_only_host_start: "Tylko host moze uruchomic wyprawe.",
    menu_role_host: "Host",
    menu_role_player: "Gracz {number}",
    menu_character_unselected: "Postac nie wybrana",
    info_hp_sp: "{hp} HP / {sp} SP",
    info_kostya_playstyle: "Wojownik z Cieniem od czystych wejsc i smiertelnych kontr.",
    info_patrick_playstyle: "Hazardzista, ktory zamienia Fartunki w wybuchowe serie z rewolweru.",
    info_jacob_playstyle: "Defensywny tank z wysokim progiem wejscia, mocno zalezny od wsparcia druzyny.",
    settings_title: "Ustawienia",
    settings_music_volume: "Glosnosc muzyki",
    settings_sfx_volume: "Glosnosc efektow",
    settings_language: "Jezyk",
    settings_hp_saturation: "Desaturacja Ekranu",
    settings_dev_mode: "Tryb Dewelopera",
    settings_on: "Wl.",
    settings_off: "Wyl.",
    language_en: "Angielski",
    language_pl: "Polski",
    loading_descending: "Zstepowanie",
    ui_level_short: "POZ",
    ui_hp_short: "HP",
    ui_sp_short: "SP",
    ui_lc_short: "LC",
    ui_sh_short: "SH",
    ui_defense_short: "OBRONA",
    ui_mobile_short: "MOBILNE",
    ui_mode_play: "Graj",
    ui_mode_inspect: "Opis",
    action_katana: "Katana",
    action_casts: "Czary",
    action_slash: "Ciecie",
    action_dash: "Doskok",
    action_lunge: "Pchniecie",
    action_decay_curse: "Klatwa\nRozpadu",
    action_crippling_stab: "Okaleczajace\nPchniecie",
    action_action_recall: "Echo Akcji",
    action_mass_infection: "Masowa\nInfekcja",
    action_ghost: "Duch",
    action_wraith: "Widmo",
    action_deep_focus: "Glebokie\nSkupienie",
    action_dark_plating: "Mroczny\nPancerz",
    action_field_promotion: "Awans\nPolowy",
    action_shadow: "Cien",
    action_kick: "Kopniecie",
    action_defend: "Obrona",
    action_ball_menu: "Pilka",
    action_support_menu: "Wsparcie",
    action_group_buff: "Buff\nGrupy",
    action_good_vibes: "Dobre Wibracje",
    action_fireball: "Ognista Pilka",
    action_slowball: "Powolna Pilka",
    action_block: "Obrona+",
    action_corner_shot: "Strzal z\nRogu",
    action_goal: "Bramka",
    action_friendly_chatter: "Przyjazna\nGadanka",
    action_guard: "Straz",
    action_group_buff_plus: "Buff Grupy+",
    action_volley: "Wolej",
    action_back: "X",
    action_coin_flip: "Rzut Moneta",
    action_revolver: "Rewolwer",
    action_aces: "Asy",
    action_inventory: "Ekwipunek",
    action_piercing_shot: "Kula z\nPrzebiciem",
    action_hollow_shot: "Kula z\nPustka",
    action_magnum_shot: "Kula z\nMagnum",
    action_bullet_storm: "Burza Kul",
    action_quickdrawer: "Szybki Bill",
    action_coin_toss: "Popis\nSpecjalny",
    action_feelin_fine: "Rzut na luz",
    action_ace_of_hearts: "As Kier",
    action_ace_of_spades: "As Pik",
    action_ace_of_diamonds: "As Karo",
    action_ace_of_clubs: "As Trefl",
    action_burger_item: "Burger",
    action_bomb_item: "Bomba",
    action_cherry_item: "Wisnia",
    action_salad_item: "Salatka",
    action_fires_item: "Frytki",
    action_ketchup_item: "Ketchup",
    battle_choose_target_prompt: "Wybierz cel\nWcisnij Shift aby anulowac",
    battle_locked_target_prompt: "Przedni cel zablokowany\nWcisnij Shift aby anulowac",
    battle_player_no_legal_move: "Brak legalnych ruchow\nZyskujesz {sp} SP i pomijasz ture",
    debug_kill_all: "Zabij Wszystko",
    debug_teleport: "Teleport",
    debug_refill_all: "Uzupelnij",
    debug_slow_mo: "Slow Mo",
    debug_skip_turn: "Pomin Ture",
    debug_counter_feedback: "COUNTER FX",
    debug_kostya_counter_egg: "Kontra 1 HP",
    word_action_singular: "akcja",
    word_action_plural: "akcje",
    upgrade_title: "Wybor Ulepszenia",
    upgrade_pick_hint: "Wybierz 1 staly bonus",
    ability_title: "Wybor Umiejetnosci",
    ability_pick_hint: "Wybierz 1 nowa zdolnosc",
    ability_confirm_prompt: "Na pewno?",
    ability_confirm_guard_solo_prompt: "Na pewno? Ta umiejetnosc jest bezuzyteczna w trybie solo",
    ability_confirm_button: "Potwierdz",
    upgrade_locked: "MAXXED",
    upgrade_luck_expertise_name: "Ekspert Szczescia",
    upgrade_luck_expertise_description: "+1% szans na orla\n+0.05 przyrostu Fartunku",
    upgrade_slot_machine_name: "Slot Machine",
    upgrade_slot_machine_description: "+7 maks. HP\n+0.5 odpornosci na Oslabienie",
    upgrade_bullet_enhancement_name: "Ulepszenie Kul",
    upgrade_bullet_enhancement_description: "+2 do obrazen Rewolweru",
    upgrade_sharper_blade_name: "Ostrzejsza Katana",
    upgrade_sharper_blade_description: "+1 do obrazen Katany\n+0.15 okna Kontry",
    upgrade_corrupted_heart_name: "Skazone Serce",
    upgrade_corrupted_heart_description: "+5 maks. HP\n+4% HP Cienia",
    upgrade_darkness_pull_name: "Przyciagniecie Mroku",
    upgrade_darkness_pull_description: "+10% przyrostu SH",
    upgrade_applied_force_name: "Przylozona Sila",
    upgrade_applied_force_description: "+1 do obrazen pilki\n+1% za zielone trafienie",
    upgrade_endurance_training_name: "Trening Wytrzymalosci",
    upgrade_endurance_training_description: "+10 maks. HP\n+1 Obrony",
    upgrade_dribbling_mastery_name: "Mistrz Dryblingu",
    upgrade_dribbling_mastery_description: "+0.1 okna uniku wrecz\n+0.1 okna uniku dystansowego",
    reward_fireball_description: "Atak pilka z rosnaca moca Ognia",
    reward_slowball_description: "Atak pilka z rosnaca moca Spowolnienia",
    reward_block_description: "Ulepsza Obrone do postawy parowania",
    reward_corner_shot_description: "Podwojne obrazenia pilki i Weakness VI",
    reward_goal_description: "Przywoluje bramke wzmacniajaca po zniszczeniu",
    reward_friendly_chatter_description: "Wsparcie z Regenem i Absorpcja",
    reward_guard_description: "Postawa ochronna wymagajaca sojusznika z Regenem SP",
    reward_group_buff_plus_description: "Silniejszy Buff Grupy z predkoscia",
    reward_volley_description: "Ryzykowny wolej z duzym zyskiem",
    reward_piercing_shot_description: "Przebija front wrogow",
    reward_hollow_shot_description: "Mocny strzal + Oznaczenie",
    reward_magnum_shot_description: "Mocny strzal + Ogluszenie",
    reward_ace_of_spades_description: "Odnawia SP i daje Regen SP IV",
    reward_ace_of_diamonds_description: "Daje druzynie Absorpcje III i Sile III",
    reward_ace_of_clubs_description: "Spowalnia i oznacza wszystkich wrogow",
    reward_bullet_storm_description: "Seria na dobicie",
    reward_quickdrawer_description: "Trafia cel i wroga za nim",
    reward_coin_toss_description: "Dwuetapowy ryzykowny strzal",
    reward_lunge_description: "Trafia obu wrogow w linii i oglusza tego z tylu",
    reward_decay_curse_description: "Katana + Rozpad III",
    reward_action_recall_description: "Cien powtarza nastepna umiejetnosc katany",
    reward_mass_infection_description: "Fala ciecia + Rozpad II na wszystkich",
    reward_ghost_description: "Tankowaty cien z podwojnym zyciem",
    reward_wraith_description: "Szklane dzialo z cecha mobilnosci",
    reward_deep_focus_description: "Pomija ture dla zabojczej postawy kontry",
    reward_crippling_stab_description: "Kradziez zycia + Spowolnienie I",
    reward_dark_plating_description: "Pelne SHP Cienia + Szybkosc II",
    inspect_katana_description: "Celuje w przedniego wroga\nZadaje [damage]{damage} obrazen[/damage]\n[good]Zielone okno:[/good] [good]+50%[/good] obrazen",
    inspect_slash_description: "Kosztuje [resource]8 SP[/resource]\nPozwala wybrac cel\nZadaje [damage]{damage} obrazen[/damage]\n[good]Zielone okno:[/good] [good]+50%[/good] obrazen",
    inspect_lunge_description: "Kosztuje [resource]16 SP[/resource]\nCeluje w [yellow]2[/yellow] wrogow w linii\nZadaje [damage]{damage} obrazen[/damage] oraz [damage]{splashDamage} obrazen[/damage] celowi za nim, nakladajac [bad]Ogluszenie V[/bad] na 2 tury na cel z tylu\n[good]Zielone okno:[/good] [good]+50%[/good] obrazen",
    inspect_decay_curse_description: "Kosztuje [resource]16 SP[/resource] i [charge]20% Cienia[/charge]\nCeluje w przedniego wroga\nZadaje [damage]{damage} obrazen[/damage] i naklada [bad]Rozpad III[/bad] na 4 tury\n[good]Zielone okno:[/good] [good]+50%[/good] obrazen",
    inspect_crippling_stab_description: "Kosztuje [resource]32 SP[/resource] i [charge]50% Cienia[/charge]\nCeluje w przedniego wroga\nZadaje [damage]{damage} obrazen[/damage], kradnie [good]{heal} HP[/good] i naklada [bad]Spowolnienie I[/bad] na 2 tury\n[good]Zielone okno:[/good] [good]+50%[/good] kradziezy zycia",
    inspect_action_recall_description: "Kosztuje [resource]24 SP[/resource] i [charge]40% Cienia[/charge]\nWymaga Cienia w walce\nNastepny ruch Katany Kostka zostaje powtorzony przez Cien, zadajac [damage]+100% bazowych obrazen[/damage]",
    inspect_mass_infection_description: "Kosztuje [resource]24 SP[/resource] i [charge]40% Cienia[/charge]\nCeluje w druzyne wrogow\nZadaje [damage]{damage} obrazen[/damage] i naklada [bad]Rozpad II[/bad] na 3 tury calej druzynie wrogow\n[good]Zielone okno:[/good] [good]+25%[/good] obrazen",
    inspect_ghost_description: "Kosztuje [resource]56 SP[/resource] i [charge]100% Cienia[/charge]\nPrzyzywa Ducha z [good]{hp} HP[/good] i [charge]{shp} SHP[/charge] do walki\nDuch atakuje przedniego wroga, zadaje [damage]{damage} obrazen[/damage] na akcje i jest bardziej prawdopodobnym celem dla wrogow",
    inspect_wraith_description: "Kosztuje [resource]56 SP[/resource] i [charge]100% Cienia[/charge]\nPrzyzywa Widmo z [good]{hp} HP[/good] i [charge]{shp} SHP[/charge] do walki\nWidmo atakuje przedniego wroga, zadaje [damage]{damage} obrazen[/damage] na akcje i jest [good]mobilne[/good]",
    inspect_deep_focus_description: "Kosztuje [resource]56 SP[/resource]\nMusi byc uzyte jako [info]pierwsza akcja[/info] tury\nPomija cala ture Kostka\nPrzez cala ture wrogow Kostek traci zolte i zielone okna uniku i moze tylko [damage]kontrowac[/damage]\nOkno kontry zyskuje [good]+2[/good] punkty, a kontry zadaja [damage]+400%[/damage] obrazen\nAtaki dystansowe wrogow tez staja sie kontrowalne przez ta ture",
    inspect_dark_plating_description: "Kosztuje [resource]32 SP[/resource] i [charge]50% Cienia[/charge]\nWymaga Cienia w walce\nUzupelnia Cienia do [charge]{shp} SHP[/charge] i naklada [good]Szybkosc II[/good] na 1 ture",
    inspect_casts_menu_description: "Otwiera Menu Czarow\nZawiera: {contains}",
    inspect_field_promotion_description: "Kosztuje [resource]48 SP[/resource] i [charge]80% Cienia[/charge]\nWymaga Cienia w walce\nUzupelnia Cieniowi [good]15% brakujacego HP[/good] i [good]10% SHP[/good]\nNaklada na Cien [strength]Sile I[/strength] na ten poziom\n[strength]Poziom Sily[/strength] stackuje sie i spada o 1 poziom za kazdy ukonczony poziom",
    inspect_shadow_description: "Kosztuje [resource]56 SP[/resource] i [charge]100% Cienia[/charge]\nPrzyzywa Cien z [good]{hp} HP[/good] i [charge]{shp} SHP[/charge] do walki\nCien atakuje przedniego wroga i zadaje [damage]{damage} obrazen[/damage] na akcje",
    inspect_kick_description: "Pozwala wybrac cel\nZadaje [damage]{damage} obrazen[/damage]\nTraf do [good]3[/good] zielonych okien, aby nakladac bonusowe obrazenia",
    inspect_defend_description: "Musi byc pierwsza akcja\nDaje [resource]4 SP[/resource], [good]+1 Obrony[/good] i [good]Odpornosc V[/good]\n[damage]Pomija ture[/damage]",
    inspect_block_description: "Musi byc pierwsza akcja\nDaje [resource]6 SP[/resource], [good]+1 Obrony[/good] i [good]Odpornosc V[/good]\nPerfekcyjne uniki wrecz PARRY, ogluszaja i daja druzynie Jacoba [good]Szybkosc I[/good] na 2 tury\n[damage]Pomija ture[/damage]",
    inspect_group_buff_description: "Kosztuje [resource]16 SP[/resource]\nNaklada [strength]Sile IV[/strength] na 4 tury",
    inspect_group_buff_upgrade_description: "Kosztuje [resource]16 SP[/resource]\nNaklada [strength]Sile VI[/strength] na 4 tury oraz [good]Szybkosc II[/good] na 2 tury",
    inspect_good_vibes_description: "Kosztuje [resource]24 SP[/resource]\nLeczy o [good]{heal} HP[/good], naklada [good]Regen HP II[/good], [resource]Regen SP II[/resource] i [cleansed]Oczyszczenie V[/cleansed] na 2 tury\nNaklada [bad]Spowolnienie II[/bad] na Jacoba na 1 ture",
    inspect_fireball_description: "Kosztuje [resource]8 SP[/resource]\nAtak pilka zadajacy [damage]{damage} obrazen[/damage]\nNaklada [bad]Ogien IV[/bad] na 4 tury, a kazde zielone trafienie daje +1 mocy",
    inspect_slowball_description: "Kosztuje [resource]8 SP[/resource]\nAtak pilka zadajacy [damage]{damage} obrazen[/damage]\nNaklada [bad]Spowolnienie I[/bad] na 4 tury, a kazde zielone trafienie daje +1 mocy",
    inspect_corner_shot_description: "Kosztuje [resource]16 SP[/resource]\nAtak pilka zadajacy [damage]{damage} obrazen[/damage]\nNaklada [bad]Oslabienie VI[/bad] na 2 tury",
    inspect_goal_description: "Kosztuje [resource]28 SP[/resource]\nPrzywoluje Bramke z [good]{hp} HP[/good]\nGdy Bramka peknie, Jacob zyskuje [good]Odpornosc IV[/good] i [absorption]Absorpcje II[/absorption] na 4 tury",
    inspect_friendly_chatter_description: "Kosztuje [resource]28 SP[/resource]\nNaklada [good]Regen HP IV[/good] i [absorption]Absorpcje II[/absorption] na 3 tury",
    inspect_guard_description: "Kosztuje [resource]32 SP[/resource]\nWymaga zyjacego sojusznika\nDaje [good]+1 Obrony[/good] na 3 tury i [resource]Regen SP I[/resource] na 3 tury",
    inspect_volley_description: "Kosztuje [resource]36 SP[/resource]\nAtak pilka zadajacy [damage]{damage} obrazen[/damage]\nKazde zielone trafienie daje [damage]+100%[/damage] obrazen, a pudla zadaja [damage]-4[/damage]\nNaklada [bad]Ogluszenie IV[/bad] nawet na 3 tury",
    inspect_coin_flip_description: "Daje [charge]{luckyChargeGain} {luckyChargeWord}[/charge]\n[good]Orzel wypada w {chance}% rzutow[/good] i daje [resource]{headsSp} SP[/resource]\nReszka daje [resource]{tailsSp} SP[/resource] i naklada [bad]Oslabienie I[/bad] na 2 tury\n[bad]Poziom Oslabienia[/bad] stackuje sie i zapisuje",
    inspect_lucky_charge_word_singular: "Fartunek",
    inspect_lucky_charge_word_plural: "Fartunki",
    inspect_revolver_menu_description: "Otwiera Menu Akcji Rewolweru\nZawiera: {contains}",
    inspect_katana_menu_description: "Otwiera Menu Akcji Katany\nZawiera: {contains}",
    inspect_ball_menu_description: "Otwiera Menu Akcji Pilki\nZawiera: [damage]{contains}[/damage]",
    inspect_support_menu_description: "Otwiera Menu Akcji Wsparcia\nZawiera: {contains}",
    inspect_aces_menu_description: "Otwiera menu akcji Asow\nZawiera: {contains}",
    inspect_inventory_menu_description: "Otwiera Menu Ekwipunku\nZawiera: {contains}",
    inspect_inventory_empty: "[bad]Pusto[/bad]",
    battle_jacob_guard_solo_warning: "STRAZ wymaga sojusznika i teraz nic nie robi",
    inspect_revolver_shot_description: "Kosztuje [charge]1 Fartunek[/charge]\nPozwala wybrac cel\nZadaje [damage]{damage} obrazen[/damage]\n[yellow]Zolte okno:[/yellow] [yellow]+25%[/yellow] obrazen\n[good]Zielone okno:[/good] [good]+50%[/good] obrazen",
    inspect_piercing_shot_description: "Kosztuje [resource]8 SP[/resource] i [charge]2 Fartunki[/charge]\nCeluje w [yellow]2[/yellow] frontowych wrogow\nZadaje [damage]{damage} obrazen[/damage]\n[yellow]Zolte okno:[/yellow] [yellow]+1[/yellow] cel\n[good]Zielone okno:[/good] [good]+2[/good] cele",
    inspect_hollow_shot_description: "Kosztuje [resource]8 SP[/resource] i [charge]2 Fartunki[/charge]\nPozwala wybrac cel\nZadaje [damage]{damage} obrazen[/damage] i naklada [marked]Oznaczenie III[/marked] na 2 tury\n[yellow]Zolte okno:[/yellow] [yellow]+25%[/yellow] obrazen\n[good]Zielone okno:[/good] [good]+50%[/good] obrazen",
    inspect_magnum_shot_description: "Kosztuje [resource]16 SP[/resource] i [charge]3 Fartunki[/charge]\nPozwala wybrac cel\nZadaje [damage]{damage} obrazen[/damage] i naklada [bad]Ogluszenie X[/bad] na 1 ture\n[yellow]Zolte okno:[/yellow] [yellow]+1[/yellow] tura\n[good]Zielone okno:[/good] [good]+2[/good] tury",
    inspect_bullet_storm_description: "Kosztuje [resource]24 SP[/resource] i [charge]4 Fartunki[/charge]\nPozwala wybrac cel\nWystrzeliwuje [yellow]3[/yellow] pociski w cel, a kazdy z nich zadaje [damage]{damage} obrazen[/damage]\n[yellow]Zolte okno:[/yellow] [yellow]+1[/yellow] pocisk\n[good]Zielone okno:[/good] [good]+3[/good] pociski",
    inspect_quickdrawer_description: "Kosztuje [resource]24 SP[/resource] i [charge]3 Fartunki[/charge]\nPozwala wybrac cel\nZadaje [damage]{damage} obrazen[/damage] celowi i wrogowi za nim, nakladajac [bad]Spowolnienie II[/bad] na 1 ture na obu\n[yellow]Zolte okno:[/yellow] [yellow]+25%[/yellow] obrazen\n[good]Zielone okno:[/good] [good]+50%[/good] obrazen",
    inspect_coin_toss_description: "Kosztuje [resource]32 SP[/resource] i [charge]5 Fartunkow[/charge]\nZuzywa [charge]1 Fartunek[/charge]\nPozwala wybrac cel\nZadaje [damage]{damage} obrazen[/damage]\n[info]Brak okna:[/info] [damage]-100%[/damage] obrazen\n[yellow]Zolte okno:[/yellow] [yellow]+600%[/yellow] obrazen\n[good]Zielone okno:[/good] [good]+900%[/good] obrazen",
    inspect_feelin_fine_description: "Kosztuje [resource]8 SP[/resource] i [charge]2 Fartunki[/charge]\nUsuwa wszystkie negatywne statusy i daje [cleansed]Oczyszczenie {cleansedPower}[/cleansed] na 3 tury\nResetuje [bad]Poziom Oslabienia[/bad]",
    inspect_ace_of_hearts_description: "Kosztuje [resource]24 SP[/resource] i [charge]4 Fartunki[/charge]\nPrzywraca [good]7 HP[/good] i naklada [good]Regen HP III[/good] na 5 tur\n[damage]Pomija ture[/damage]",
    inspect_ace_of_spades_description: "Kosztuje [charge]3 Fartunki[/charge]\nPrzywraca [resource]7 SP[/resource] i naklada [resource]Regen SP IV[/resource] na 3 tury",
    inspect_ace_of_diamonds_description: "Kosztuje [resource]16 SP[/resource] i [charge]3 Fartunki[/charge]\nNaklada [absorption]Absorpcje III[/absorption] oraz [strength]Sile III[/strength] na 4 tury dla druzyny",
    inspect_ace_of_clubs_description: "Kosztuje [resource]16 SP[/resource] i [charge]3 Fartunki[/charge]\nNaklada [bad]Spowolnienie I[/bad] oraz [marked]Oznaczenie III[/marked] na 4 tury dla druzyny wrogow",
    inspect_burger_item_description: "Przywraca [good]10 HP[/good] i naklada [good]Regen HP I[/good] na 2 tury",
    inspect_bomb_item_description: "Zadaje [damage]25 obrazen[/damage] wszystkim wrogom i naklada [bad]Ogluszenie X[/bad] na 2 tury\nNaklada [bad]Spowolnienie II[/bad] na 1 ture na uzytkownika",
    inspect_cherry_item_description: "Naklada [bad]Podpalenie V[/bad] na 2 tury wszystkim wrogom\nNaklada [strength]Sile X[/strength] na 2 tury na uzytkownika",
    inspect_salad_item_description: "Usuwa wszystkie negatywne statusy z uzytkownika\nNaklada [cleansed]Oczyszczenie X[/cleansed] na 3 tury",
    inspect_fires_item_description: "Przywraca [resource]10 SP[/resource] i naklada [resource]Regen SP I[/resource] na 2 tury",
    inspect_ketchup_item_description: "Przywraca [good]15 HP[/good]\nNaklada [strength]Sile IV[/strength] na 3 tury wszystkim sojusznikom, w tym przywolaniom",
    battle_burger_item: "Burger przywrocil 10 HP i nalozyl Regen HP I na 2 tury",
    battle_salad_item: "Salatka usunela negatywne statusy i nalozyla Oczyszczenie {power} na {turns} tury",
    battle_cherry_item: "Wisnia nalozyla Podpalenie {firePower} na {fireTurns} tury oraz Sile {strengthPower} na {strengthTurns} tury",
    battle_bomb_item: "Bomba zadala {damage} obrazen, nalozyla Ogluszenie {stunPower} na {stunTurns} tury i Spowolnienie {slowPower} na {slowTurns} ture",
    battle_fires_item: "Frytki przywrocily {sp} SP i nalozyly Regen SP {power} na {turns} tury",
    battle_ketchup_item: "Ketchup przywrocil {heal} HP i nalozyl Sile {power} na {turns} tury wszystkim sojusznikom"
  }
};

let currentLanguage = loadStoredLanguage();
const listeners = new Set();

export function t(key, vars = {}) {
  const languageTable = TRANSLATIONS[currentLanguage] ?? TRANSLATIONS[DEFAULT_LANGUAGE];
  const template = languageTable[key] ?? TRANSLATIONS[DEFAULT_LANGUAGE][key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, token) => String(vars[token] ?? ""));
}

export function getLanguage() {
  return currentLanguage;
}

export function setLanguage(language) {
  if (!TRANSLATIONS[language]) {
    currentLanguage = DEFAULT_LANGUAGE;
  } else {
    currentLanguage = language;
  }

  try {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, currentLanguage);
  } catch {
    // Ignore storage failures.
  }

  listeners.forEach((listener) => listener(currentLanguage));
}

export function getSupportedLanguages() {
  return Object.keys(TRANSLATIONS);
}

export function onLanguageChange(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function loadStoredLanguage() {
  try {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored && TRANSLATIONS[stored]) {
      return stored;
    }
  } catch {
    // Ignore storage failures.
  }

  return DEFAULT_LANGUAGE;
}
